package ServerSide;


/**
* ServerSide/Server.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Monday, February 20, 2023 7:38:22 o'clock PM EST
*/

public interface Server extends ServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Server
