package ServerSide;


/**
* ServerSide/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Thursday, February 23, 2023 4:12:46 o'clock PM EST
*/

public interface ServerOperations 
{
  String verifyID (String ID);
  String verifyMovieID (String movieID);
  String addMovieSlots (String movieID, String movieName, int bookingcapacity);
  String removeMovieSlots (String movieID, String movieName);
  String listMovieShows (String movieName);
  String addadmin (String adminID);
  String bookMovieTicket (String CustomerID, String movieID, String movieName, int Numberoftickets);
  String getBookingSchedule (String CustomerID);
  String cancelMovieTickets (String CustomerID, String movieID, String movieName, int Numberoftickets);
  void serverlogwriter (String requesttype, String ID, boolean status);
  String exchangeTickets (String customerID, String movieID, String movieName, String new_movieID, String new_movieName, int numberOfTickets);
  void bookingservertoserver (String data);
} // interface ServerOperations
