package ServerSide;

/**
* ServerSide/ServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Thursday, February 23, 2023 4:12:46 o'clock PM EST
*/

public final class ServerHolder implements org.omg.CORBA.portable.Streamable
{
  public ServerSide.Server value = null;

  public ServerHolder ()
  {
  }

  public ServerHolder (ServerSide.Server initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServerSide.ServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServerSide.ServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServerSide.ServerHelper.type ();
  }

}
