package ServerSide;


/**
* ServerSide/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Monday, February 20, 2023 7:38:22 o'clock PM EST
*/

public interface ServerOperations 
{
  String verifyMovieID (String movieID);
  String addMovieSlots (String movieID, String movieName, int bookingcapacity);
  String removeMovieSlots (String movieID, String movieName);
  String listMovieShows (String movieName);
  String addadmin (String adminID);
  String bookMovieTicket (String CustomerID, String movieID, String movieName, int Numberoftickets);
  String getBookingSchedule (String CustomerID);
  String cancelMovieTickets (String CustomerID, String movieID, String movieName, int Numberoftickets);
} // interface ServerOperations
